### ISSUE TITLE
Allow time sampling less than 328 seconds (esp. for DPA/DEA models)

### ISSUE THREAD

**Issue by taldcroft** [sot/xija#57]
Currently there is a parameter in the xija `Model` class init to set the time sampling to 328 sec, but there is also a [warning to not change it](https://github.com/sot/xija/blob/cc03c7d15dd3bbf8de190b354417c22795e9bfbb/xija/model.py#L76).

I don't remember exactly why that warning is there or what might break.

There is now an operational driver to consider using finer sampling, namely the DPA/DEA models where there can be significant temperature changes due to very short FEP state changes.  E.g. of order 0.3 C for a several minutes with zero FEPs.  This can actually fall entirely within a 328 sec bin and get lost.  Conversely a short time with zero FEPs can cross a bin boundary and effectively get counted as 328 sec at zero FEPs (thus overpredicting the effective cooling).

Suggesting here that @jzuhone have a look into whether some models like DPA could be run with finer time sampling.

I also looked the possibility of variable time sample, e.g. make a new bin whenever the state changes (in addition to regular 328 sec bin boundaries).  I think this is somewhat difficult due to the RK2 integration in core.c.

**Comment by jeanconn** [comment]
Also https://github.com/sot/xija/pull/48 .

**Comment by jzuhone** [comment]
Happy to look at this.

**Comment by jeanconn** [comment]
Closed by #48
