### ISSUE TITLE
Color assignments to model vs data traces on plots

### ISSUE THREAD

**Issue by Gregg140** [sot/xija#85]
The color change to make model traces red and data traces blue was not carried through to all available plots. An example is the

dpa_power data__time plot for the 1DPAMZT model

**Comment by jzuhone** [comment]
This is mine, I can fix it

**Comment by jzuhone** [comment]
@Gregg140 can you check to see if this is still an issue? I'm not seeing that it is.

**Comment by Gregg140** [comment]
Looks fixed

**Comment by jzuhone** [comment]
@Gregg140 fixed in master or in my branch? Because if it's only on my branch we shouldn't close the issue yet.
