### ISSUE TITLE
Allow pathlib Path/PosixPath as model_spec

### ISSUE THREAD

**Issue by jeanconn** [sot/xija#98]
It looks like:

https://github.com/sot/xija/blob/64b81084e1a4c21c500eb8cd7fdb1d12dc068e73/xija/model.py#L108

only allows model_spec files as string filenames.

**Comment by taldcroft** [comment]
There must be something else happening.  The built-in `open` definitely accepts a `Path` or `PosixPath` object.

**Comment by taldcroft** [comment]
The problem is actually here:
https://github.com/sot/xija/blob/64b81084e1a4c21c500eb8cd7fdb1d12dc068e73/xija/model.py#L107

**Comment by jeanconn** [comment]
Right, I saw that and understood the reason why, but should have linked the line up.

**Comment by jeanconn** [comment]
And then a question about if six should be removed, if this should be handled with a try-to-read or some such, or if the user should just do what I did in my dev perigee_health_plots and str(PosixPath).
